# --
# config
#
# dcase 2023
# task 5: Few-shot Bioacoustic Event Detection

# wav reader
audio_file_reader:

  # path, files and folders
  src_path: './dataset_link_dcase2023_root/'

  # file subdirs
  subdirs:
    train: 'Training_Set/'
    val: 'Validation_Set/'

  # file extension
  ext: '.wav'
  anno_ext: '.csv'

  # training subdir
  #subdir_tain: 'Training_Set/'
  subdir_train_class_folders: ['BV', 'HT', 'JD', 'MT', 'WMW']
  choose_train_classes: ['BV']

  # validation subdir
  #subdir_val: 'Validation_Set/'
  subdir_val_class_folders: ['HB', 'ME', 'PB']
  choose_val_classes: ['HB']

  # output path
  out_path: "./ignore/"
  out_folder: "wav_data/"

  # extractions
  split_in_sec: 60

  # redo extraction
  redo_extraction: false


dataset:

  # path
  #root_path: '/home/christian/Downloads/datasets/dcase2023_task5/'
  root_path: './dataset_link_dcase2023_root/'
  subdir_tain: 'Training_Set/'
  subdir_val: 'Validation_Set/'

  # class anno files
  class_anno_csv_files: ['DCASE2022_task5_Training_set_classes.csv', 'DCASE2022_task5_Validation_set_classes.csv']

  # training classes
  all_train_classes: ['BV', 'HT', 'JD', 'MT', 'WMW']
  choose_train_classes: ['BV']

  # validation classes
  all_val_classes: ['HB', 'ME', 'PB']
  choose_val_classes: ['HB', 'ME', 'PB']

  # file extensions
  audio_file_ext: '.wav'
  anno_file_ext: '.csv'

  # extractions
  split_in_sec: 60

  # output path
  out_path: "./ignore/"
  out_folder: "wav_data/"